version: '3'

services:
    php-fpm:
        build:
            context: ../
            dockerfile: ./docker/php-fpm/Dockerfile
        privileged: no
        container_name: "php-fpm"
        volumes:
            - ./php-fpm/config/php:/etc/php
            - ${PWD}/../composer.json:/var/www/html/composer.json
            - ../src:/var/www/html/public
            - ../private:/var/www/html/private
            - vendor:/var/www/html/vendor
            - php-fpm-sock:/run/php-fpm
        networks:
            webnet:
                ipv4_address: 172.25.0.20
    apache2:
        build:
            context: ./apache2
            dockerfile: Dockerfile
        privileged: no
        container_name: "apache2"
        volumes:
            - ./logs:/var/log/apache2
            - ./apache2/config/vhosts:/etc/httpd/vhosts/
            - ./apache2/config/conf:/etc/httpd/conf
            - ../src:/var/www/html/public
            - vendor:/var/www/html/vendor
            - php-fpm-sock:/run/php-fpm
        ports:
            - "8082:80"
        networks:
            webnet:
                ipv4_address: 172.25.0.22
    # mysql:
    #     build:
    #         context: ./mysql
    #         dockerfile: Dockerfile
    #     privileged: no
    #     container_name: "mysql"
    #     volumes:
    #         - mysql-data:/var/lib/mysql
    #     networks:
    #         webnet:
    #             ipv4_address: 172.25.0.21
    #
volumes:
    php-fpm-sock:
    vendor:
      driver: local
      driver_opts:
        type: none
        device: ${PWD}/${VENDOR_PATH}
        o: bind
networks:
    webnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/24
