version: '3'

services:
    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        privileged: no
        container_name: "php-fpm"
        volumes:
            - ./php-fpm/php-fpm.d:/etc/php/php-fpm.d
            - ../src:/var/www/html/public
            - ../vendor:/var/www/html/vendor
            - php-fpm-sock:/run/php-fpm
        networks:
            webnet:
                ipv4_address: 172.25.0.20
    apache:
        build:
            context: ./apache2
            dockerfile: Dockerfile
        privileged: no
        container_name: "apache2"
        volumes:
            - ./logs:/var/log/apache2
            - ./apache2/vhosts/:/etc/apache2/sites-enabled/
            - ../src:/var/www/html/public
            - ../vendor:/var/www/html/vendor
            - php-fpm-sock:/run/php-fpm
        ports:
            - "8082:80"
        networks:
            webnet:
                ipv4_address: 172.25.0.22
    # mysql:
    #     build:
    #         context: ./mysql
    #         dockerfile: Dockerfile
    #     privileged: no
    #     container_name: "mysql"
    #     volumes:
    #         - mysql-data:/var/lib/mysql
    #     ports:
    #         - "3307:3306"
    #     networks:
    #         webnet:
    #             ipv4_address: 172.25.0.21
    #
volumes:
    php-fpm-sock:
networks:
    webnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/24
